# -*- coding: utf-8 -*-
"""HistogramEqualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PkK-PfPXlNUdEdLWFoy2lTZYFBAHd5E2

#Libraries
"""

pip install opencv-python

import numpy as np
import cv2
import matplotlib.pyplot as plt
print("OpenCV-Python Version %s" % cv2.__version__)

"""#Histogram Equalization function"""

def hist_equ (image,noBins):
  # create figure
  fig = plt.figure(figsize=(10,7))
  # setting values to rows and column variables
  rows = 2
  columns = 2

  # Adds a subplot at the 1st position
  fig.add_subplot(rows, columns, 1)

  #read the image
  img = cv2.imread(image,0)
  #If the image path is wrong, the resulting img will be none
  if img is None:
    print('Open Error')
  else:
    print('Image Loaded')

    plt.imshow(img,cmap='gray')
    plt.axis('off')
    plt.margins(0.015, tight=True)
    plt.title("original image")

    # Adds a subplot at the 2nd position
    fig.add_subplot(rows, columns, 2)

    plt.hist(img.ravel(), noBins, (0, noBins))
    plt.axis('off')
    plt.margins(0.015, tight=True)
    plt.title("Histogram of original image")

    # Adds a subplot at the 3rd position
    fig.add_subplot(rows, columns, 3)

    qu = cv2.equalizeHist(img)
    plt.imshow(qu,cmap='gray')
    plt.axis('off')
    plt.margins(0.015, tight=True)
    plt.title("image after histogram equalization")

    # Adds a subplot at the 4th position
    fig.add_subplot(rows, columns, 4)

    plt.hist(qu.ravel(), noBins, (0, noBins))
    plt.axis('off')
    plt.title("Histogram Equalization")
    plt.margins(0.015, tight=True)
    return

hist_equ('jetplane.tif',256)

hist_equ('jetplane.tif',128)

hist_equ('jetplane.tif',64)